#!/bin/sh
#
# MAKEDEV - create BDM character special file
#
cd /dev
for port in 0 1 2 3
do
name=bdmcpu32${port}
if [ ! -c ${name} ]
then
  mknod ${name} c 34 `expr 0 + ${port}`
  chmod 666 ${name} 
fi
name=bdmcf${port}
if [ ! -c ${name} ]
then
  mknod ${name} c 34 `expr 4 + ${port}`
  chmod 666 ${name}
fi
name=bdmicd${port}
if [ ! -c ${name} ]
then
  mknod ${name} c 34 `expr 8 + ${port}` 
  chmod 666 ${name}
fi
done
