.\"
.Dd June 19, 1997
.Dt BDM 8
.Os FreeBSD
.Sh NAME
.Nm bdm
.Nd load the background debug module driver kernel module
.Sh SYNOPSIS
.Nm bdm
.Sh DESCRIPTION
The
.Nm
utility loads the background debug module driver kernel module.
.Sh FILES
.Bl -tag -width /lkm/bdm_mod.o 
.It Pa /lkm/bdm_mod.o
background debug module loadable kernel module.
.Sh "SEE ALSO"
.Xr lkm 4 ,
.Xr modload 8
